# roles/samba/defaults/main.yml
---

samba_workgroup: 'OPTIMAPLUS'
samba_server_string: 'NAS %m'
samba_log_size: 5000
samba_security: 'user'
samba_passdb_backend: 'tdbsam'
samba_map_to_guest: 'bad user'
samba_load_printers: 'no'
samba_load_homes: 'no'
samba_shares_root: '/srv/shares'
