# roles/httpd/tasks/main.yml
---

- name: Ensure Apache is installed
  sudo : True 
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - mod_ssl
  tags: httpd

- name: Install PHP support if needed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - php
    - php-xml
  when: httpd_scripting is defined and httpd_scripting == "php"
  tags: httpd

- name: Install Git
  yum:
    name: "{{ item }}"
    state : present
  with_items:
    - git

- name: Ensure Apache is always running
  sudo : True
  service:
    name: httpd
    state: started
    enabled: yes
  tags: httpd

- name: Install main configuration file
  sudo : True
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  tags: httpd

- name: Install mod_ssl configuration file
  sudo : True
  template:
    src: ssl.conf.j2
    dest: /etc/httpd/conf.d/ssl.conf
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  tags: httpd

- name : Clean existing website content
  file: path=/var/www/html state=absent

- name : Clone Git repository
  git: >
    dest=/var/www/html
    repo=https://github.com/johntjampens/Demo_website.git
    update=no
  notify: restart httpd
  tags: httpd